name: "Richardson Lab"
description: "This is the official web page for the Richardson Lab."

url: "http://hilaryrichardson.github.io"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        people:
                output: true
        publications:
                output: true
        alumni:
                output: true
        sep:
                output: true
        visitors:
                output: true
